import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import Navbar from "../../components/navbar";
import Footer from "../../components/footer";
import { getPublishedArticleBySlug, getRelatedArticles } from "../../../lib/bichridigital-articles";
import { readingMinutes } from "../../../lib/article-format";
import { ARTICLE_CATEGORY_LABELS } from "../../../types/bichridigital-article";
import ArticleCard from "../article-card";
import ArticleMarkdown, { extractHeadings } from "./article-markdown";
import ShareButtons from "./share-buttons";

type Props = { params: Promise<{ slug: string }> };
const BASE = "https://www.bichridigital.com";
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const article = await getPublishedArticleBySlug(slug); if (!article) return { title: "Article introuvable", robots: { index: false, follow: false } }; const url = `${BASE}/conseils/${article.slug}`; return { title: article.seo_title ?? article.title, description: article.seo_description ?? article.excerpt, alternates: { canonical: url }, robots: { index: true, follow: true }, authors: [{ name: article.author_name }], openGraph: { title: article.seo_title ?? article.title, description: article.seo_description ?? article.excerpt, url, siteName: "Bichridigital Agency", locale: "fr_SN", type: "article", publishedTime: article.published_at ?? undefined, modifiedTime: article.updated_at, authors: [article.author_name], images: article.cover_url ? [{ url: article.cover_url, alt: article.title }] : undefined }, twitter: { card: "summary_large_image", title: article.seo_title ?? article.title, description: article.seo_description ?? article.excerpt, images: article.cover_url ? [article.cover_url] : undefined } }; }

export default async function ArticlePage({ params }: Props) { const { slug } = await params; const article = await getPublishedArticleBySlug(slug); if (!article) notFound(); const related = await getRelatedArticles(article.id, article.category); const headings = extractHeadings(article.content); const url = `${BASE}/conseils/${article.slug}`; const date = article.published_at ? new Intl.DateTimeFormat("fr-FR", { dateStyle: "long", timeZone: "Africa/Dakar" }).format(new Date(article.published_at)) : ""; const articleLd = { "@context": "https://schema.org", "@type": "Article", headline: article.title, description: article.seo_description ?? article.excerpt, image: article.cover_url ? [article.cover_url] : undefined, datePublished: article.published_at, dateModified: article.updated_at, author: { "@type": "Organization", name: article.author_name }, publisher: { "@type": "Organization", name: "Bichridigital Agency", url: BASE }, mainEntityOfPage: url }; const breadcrumbLd = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Accueil", item: BASE }, { "@type": "ListItem", position: 2, name: "Conseils", item: `${BASE}/conseils` }, { "@type": "ListItem", position: 3, name: article.title, item: url }] };
  return <><Navbar /><main className="min-h-screen bg-[#020B2E] px-5 pb-24 pt-32 text-white"><article className="mx-auto max-w-5xl"><nav className="flex flex-wrap gap-2 text-sm text-white/50"><Link href="/">Accueil</Link><span>/</span><Link href="/conseils">Conseils</Link><span>/</span><span className="text-white/75">{article.title}</span></nav><header className="mt-10"><p className="font-black uppercase tracking-[.2em] text-[#FCCD12]">{ARTICLE_CATEGORY_LABELS[article.category]}</p><h1 className="mt-5 text-4xl font-black leading-tight md:text-7xl">{article.title}</h1><p className="mt-7 text-xl leading-9 text-white/65">{article.excerpt}</p><div className="mt-7 flex flex-wrap gap-5 text-sm text-white/50"><span>{article.author_name}</span><time dateTime={article.published_at ?? undefined}>{date}</time><span>{readingMinutes(article.content)} min de lecture</span></div><div className="mt-6"><ShareButtons title={article.title} url={url} /></div></header>{article.cover_url && <div className="relative mt-12 aspect-video overflow-hidden rounded-[32px]"><Image src={article.cover_url} alt={`Couverture de ${article.title}`} fill priority sizes="(max-width: 1024px) 100vw, 1024px" className="object-cover" /></div>}{headings.length > 1 && <aside className="mt-12 rounded-[28px] border border-white/10 bg-white/5 p-6"><h2 className="font-black text-[#FCCD12]">Dans cet article</h2><ol className="mt-4 space-y-2 text-white/65">{headings.map((heading, index) => <li key={`${heading.id}-${index}`} className={heading.level === 3 ? "pl-5" : ""}><a href={`#${heading.id}`} className="hover:text-white">{heading.label}</a></li>)}</ol></aside>}<div className="mt-14"><ArticleMarkdown content={article.content} /></div><section className="mt-16 rounded-[32px] bg-[#0024FF] p-8 md:p-12"><h2 className="text-3xl font-black">Un projet à concrétiser ?</h2><p className="mt-4 max-w-2xl leading-7 text-white/75">Bichridigital vous accompagne en communication, production audiovisuelle et développement web.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/services" className="rounded-full bg-[#FCCD12] px-6 py-3 font-black text-[#020B2E]">Découvrir nos services</Link><Link href="/contact" className="rounded-full border border-white/30 px-6 py-3 font-black">Nous contacter</Link></div></section></article>{related.length > 0 && <section className="mx-auto mt-20 max-w-7xl"><h2 className="text-3xl font-black">À lire aussi</h2><div className="mt-8 grid gap-6 md:grid-cols-3">{related.map((item) => <ArticleCard key={item.id} article={item} />)}</div></section>}<script type="application/ld+json">{JSON.stringify(articleLd).replace(/</g, "\\u003c")}</script><script type="application/ld+json">{JSON.stringify(breadcrumbLd).replace(/</g, "\\u003c")}</script></main><Footer /></>;
}
