import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
import { getFeaturedArticle, getPublishedArticlePage } from "../../lib/bichridigital-articles";
import { readingMinutes } from "../../lib/article-format";
import { ARTICLE_CATEGORY_LABELS } from "../../types/bichridigital-article";
import ArticleGrid from "./article-grid";

const description = "Conseils pratiques de Bichridigital sur la communication digitale, l’audiovisuel, la photographie, le design, le web et le SEO.";
export const metadata: Metadata = { title: "Conseils Bichridigital", description, alternates: { canonical: "/conseils" }, robots: { index: true, follow: true }, openGraph: { title: "Conseils Bichridigital", description, url: "https://www.bichridigital.com/conseils", siteName: "Bichridigital Agency", locale: "fr_SN", type: "website", images: [{ url: "/logo.png", width: 1200, height: 630, alt: "Conseils Bichridigital" }] }, twitter: { card: "summary_large_image", title: "Conseils Bichridigital", description, images: ["/logo.png"] } };

export default async function ConseilsPage({ searchParams }: { searchParams: Promise<{ page?: string }> }) {
  const query = await searchParams; const parsedPage = Number(query.page ?? "1"); const page = Number.isInteger(parsedPage) && parsedPage > 0 ? parsedPage : 1;
  const [{ articles, hasMore }, featured] = await Promise.all([getPublishedArticlePage(page), getFeaturedArticle()]);
  return <><Navbar /><main className="min-h-screen bg-[#020B2E] px-5 pb-24 pt-32 text-white"><section className="mx-auto max-w-7xl"><div className="max-w-4xl py-16"><p className="font-black uppercase tracking-[.28em] text-[#FCCD12]">L’expertise en partage</p><h1 className="mt-5 text-5xl font-black leading-none md:text-7xl">Conseils <span className="text-[#FCCD12]">Bichridigital</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/65">Depuis 2019, Bichridigital partage son expérience de terrain pour vous aider à mieux communiquer, produire et développer votre présence numérique.</p></div>
    {featured && <article className="grid overflow-hidden rounded-[36px] border border-[#FCCD12]/25 bg-gradient-to-br from-[#0024FF]/25 to-white/[.04] lg:grid-cols-2"><div className="relative min-h-72 bg-[#08143D]">{featured.cover_url ? <Image src={featured.cover_url} alt={`Couverture de ${featured.title}`} fill priority sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover" /> : <div className="flex h-full items-center justify-center font-black uppercase tracking-[.25em] text-white/25">Conseil à la une</div>}</div><div className="flex flex-col justify-center p-8 md:p-12"><p className="text-sm font-black uppercase tracking-[.18em] text-[#FCCD12]">À la une · {ARTICLE_CATEGORY_LABELS[featured.category]}</p><h2 className="mt-4 text-3xl font-black md:text-5xl">{featured.title}</h2><p className="mt-5 leading-8 text-white/65">{featured.excerpt}</p><p className="mt-5 text-sm text-white/45">{featured.author_name} · {readingMinutes(featured.content)} min de lecture</p><Link href={`/conseils/${featured.slug}`} className="mt-7 w-fit rounded-full bg-[#FCCD12] px-6 py-3 font-black text-[#020B2E]">Découvrir l’article</Link></div></article>}
    <section className="mt-20"><div><p className="font-black uppercase tracking-[.2em] text-[#FCCD12]">Nos publications</p><h2 className="mt-3 text-4xl font-black">Des ressources utiles et concrètes</h2></div>{articles.length ? <><ArticleGrid articles={articles} /><nav className="mt-10 flex justify-center gap-3" aria-label="Pagination des articles">{page > 1 && <Link href={`/conseils?page=${page - 1}`} className="rounded-full border border-white/20 px-5 py-3 font-bold">Page précédente</Link>}{hasMore && <Link href={`/conseils?page=${page + 1}`} className="rounded-full bg-[#FCCD12] px-5 py-3 font-black text-[#020B2E]">Voir plus</Link>}</nav></> : <p className="mt-10 rounded-[30px] border border-white/10 bg-white/5 p-12 text-center text-white/60">{page === 1 ? "Les premiers Conseils Bichridigital seront bientôt publiés." : "Aucun autre article publié."}</p>}</section></section></main><Footer /></>;
}
